# Generated by Django 3.2.4 on 2023-07-20 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='channels.channel', verbose_name='کانال')),
                ('ghased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='accounts.ghased', verbose_name='قاصد')),
            ],
            options={
                'verbose_name': 'عضو کانال',
                'verbose_name_plural': 'اعضای کانال\u200cها',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_subscriptions', to='subscribe.subscriber', verbose_name='عضو کانال')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_subscriptions', to='channels.subscription', verbose_name='اشتراک')),
            ],
            options={
                'verbose_name': 'عضو کانال',
                'verbose_name_plural': 'اعضای کانال\u200cها',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('ghased', 'channel'), name='unique_subscriber_if_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='purchasedsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('subscriber', 'subscription'), name='unique_purchased_subscription_if_not_deleted'),
        ),
    ]
