# Generated by Django 3.2.4 on 2023-07-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='purchasedsubscription',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='purchasedsubscription',
            name='unique_purchased_subscription_if_not_deleted',
        ),
        migrations.RemoveField(
            model_name='purchasedsubscription',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='purchasedsubscription',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='subscriptionstatus',
            name='subscriber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_status', to='subscribe.subscriber', verbose_name='عضو کانال'),
        ),
    ]
