# Generated by Django 3.2.4 on 2023-08-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20230724_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionstatus',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ انقضا'),
        ),
    ]
