# Generated by Django 3.2.4 on 2023-08-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20230819_0009'),
        ('subscribe', '0003_alter_subscriptionstatus_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedsubscription',
            options={'verbose_name': 'اشتراک خریداری شده', 'verbose_name_plural': 'اشتراک\u200cهای خریداری شده'},
        ),
        migrations.CreateModel(
            name='PurchasedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_contents', to='channels.channelcontent', verbose_name='محتوا')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_contents', to='subscribe.subscriber', verbose_name='عضو کانال')),
            ],
            options={
                'verbose_name': 'محتوای خریداری شده',
                'verbose_name_plural': 'محتواهای خریداری شده',
            },
        ),
    ]
