version: '3.3'

services:
  ghasedak:
    image: ghcr.io/ood-ghasedak/backend:latest
    env_file:
      - .env
    command: ['runserver', '0.0.0.0:8000']
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:13.6-bullseye
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
