version: '3.8'

services:
  db:
    image: postgres:13.6-bullseye
    environment:
      POSTGRES_DB: ghasedak
      POSTGRES_USER: ghasedak
      POSTGRES_PASSWORD: ghasedak
    ports:
      - "5499:5432"
    volumes:
      - "/home/postgres/ghasedak:/var/lib/postgresql/data"
