version: '3.8'

services:
  ghasedak:
    build:
      context: .
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: ghasedak
      DB_USER: ghasedak
      DB_PASSWORD: ghasedak
      DJANGO_SECRET_KEY: "django-insecure-xf787mwonq2s5*i%npk!-tqu8qgsn_g0fe*%vgsrfel7zvr_s1"
    command: ['runserver', '0.0.0.0:8000']
    ports:
      - "8000:8000"
    volumes:
      - ".:/src/"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.6-bullseye
    environment:
      POSTGRES_DB: ghasedak
      POSTGRES_USER: ghasedak
      POSTGRES_PASSWORD: ghasedak
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ghasedak" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
