# Generated by Django 3.2.4 on 2023-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, verbose_name='موجودی'),
        ),
    ]
