# Generated by Django 3.2.4 on 2023-08-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionentry',
            name='amount',
            field=models.BigIntegerField(verbose_name='مقدار'),
        ),
    ]
