# Generated by Django 3.2.4 on 2023-07-23 14:59

from django.db import migrations, models
import utility.django


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ghased_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghased',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[utility.django.GhasedakMobileNumberValidator()], verbose_name='شماره همراه'),
        ),
    ]
