# Generated by Django 3.2.4 on 2023-07-24 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ghased_phone_number'),
        ('channel_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='channeladmin',
            managers=[
                ('concrete_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='channelowner',
            managers=[
                ('concrete_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='channeladmin',
            name='created',
        ),
        migrations.RemoveField(
            model_name='channeladmin',
            name='ghased',
        ),
        migrations.RemoveField(
            model_name='channeladmin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='channeladmin',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='channeladmin',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='channelowner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='channelowner',
            name='ghased',
        ),
        migrations.RemoveField(
            model_name='channelowner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='channelowner',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='channelowner',
            name='updated',
        ),
        migrations.CreateModel(
            name='ChannelManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('ghased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channelmanager', to='accounts.ghased', verbose_name='قاصد')),
            ],
            options={
                'verbose_name': 'گرداننده کانال',
                'verbose_name_plural': 'گردانندگان کانال',
            },
            managers=[
                ('concrete_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='channeladmin',
            name='channelmanager_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='channel_management.channelmanager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelowner',
            name='channelmanager_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='channel_management.channelmanager'),
            preserve_default=False,
        ),
    ]
