# Generated by Django 3.2.4 on 2023-08-21 15:45

from django.db import migrations
import utility.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0002_auto_20230724_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeladmin',
            name='share',
            field=utility.models.fields.PercentageField(blank=True, null=True, verbose_name='درصد سهم'),
        ),
    ]
