# Generated by Django 3.2.4 on 2023-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='duration',
            new_name='duration_choice',
        ),
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default=1, verbose_name='بیوگرافی کانال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default=1, max_length=256, unique=True, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
