# Generated by Django 3.2.4 on 2023-08-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20230724_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.PositiveBigIntegerField(default=1, verbose_name='قیمت اشتراک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration_choice',
            field=models.CharField(choices=[('one month', 'یک ماهه'), ('three month', 'سه ماهه'), ('six month', 'شش ماهه'), ('twelve month', 'دوازده ماهه')], max_length=128, verbose_name='دوره'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('channel', 'duration_choice'), name='unique_duration_for_channel'),
        ),
    ]
