# Generated by Django 3.2.4 on 2023-08-18 18:24

import channels.models.channel_content
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20230803_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelcontent',
            name='updated',
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, verbose_name='برای کاربران اشتراکی؟'),
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه محتوا'),
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='محتوای متنی'),
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='تیتر محتوا'),
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=channels.models.channel_content.content_file_upload_to, verbose_name='فایل محتوا')),
                ('file_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صوت')], max_length=64)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='channels.channelcontent', verbose_name='کانال')),
            ],
            options={
                'verbose_name': 'فایل محتوا',
                'verbose_name_plural': 'فایل\u200cهای محتواها',
            },
        ),
    ]
