# Generated by Django 3.2.4 on 2023-08-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20230818_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelcontent',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت محتوا'),
        ),
    ]
